generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Asso
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          asso
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, login, PoleName, Type, url_site, active, charte_info]
      filter:
        display: [name, login, pole_id]
      form:    ~
      edit:    ~
      new:     ~
