all:
  sf_guard_plugin:
    allow_login_with_email: true
    remember_key_expiration_age:  604800   # 7 days in seconds
    remember_cookie_name:         portailSiMDERememberMe
  gallerynePlugin:
    uploader:
       default:
        relation_type: related_table
        aggregate_entity_class_name: Gallery
        entity_aggregate_columnid: gallery_id
        entity_filename_column: filename
        entity_size_column: size
        entity_file_kinds:
          - Photos
        photos_max_number: 10
        photos_unit_max_weight: 1100000
        photos_max_weight: 21000000
 
        global_max_weight: 21000000
        main_path: /uploads/gallery
 
        min_file_size: 1 
        max_file_size: 1000000000
  cas:
    # Exemple for https://cas-server-name:8443/cas-path
    server_name: 'cas.utc.fr'
    server_port: 443
    server_path: 'cas'
    # SSL certificat location, can be:
    #  relative to sf_root_dir, ex:    "data/cas/cert/mycert.pem"
    #  absolute ex:                    "/usr/var/certif/xxx.pem"
    #  disabled for dev context ex:    false
    server_cert: "../data/cas.pem"
  sfImageTransformPlugin:
    default_adapter: GD
    default_image: default.jpg
    mime_type:
      auto_detect: true
      library: gd_mime_type
  portail:
    current_semestre: 2
    default_join_role: 3
  sfXssSafePlugin:
    definition:

      HTML:
        DefinitionID:              'portail definition' 
        DefinitionRev:             1


dev:
  cas:
    server_cert: false
