all:
  sf_guard_plugin:
    allow_login_with_email: true
    remember_key_expiration_age:  604800   # 7 days in seconds
    remember_cookie_name:         portailSiMDERememberMe
  sfXssSafePlugin:
    definition:
      HTML:
        DefinitionID:              'portail definition' 
        DefinitionRev:             1
      AutoFormat:
        Custom:                    'Linkify'

dev:
  cas:
    server_cert: false
