# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: asso, action: index }
  
  
assos_list:
  url:   /asso
  param: { module: asso, action: index }

assos_list_pole:
  url:   /asso/pole/:id
  class: sfDoctrineRoute
  param: { module: asso, action: list }
  options: { model: Pole, type: object }

assos_show:
  url:   /asso/show/:id
  class: sfDoctrineRoute
  param: { module: asso, action: show }
  options: { model: Asso, type: object }
  
articles_list:
  url:   /article
  param: { module: article, action: index }
  
articles_list_asso:
  url:   /article/asso/:id
  class: sfDoctrineRoute
  param: { module: article, action: list }
  options: { model: Asso, type: object }
  
article_show:
  url:   /article/show/:id
  class: sfDoctrineRoute
  param: { module: article, action: show }
  options: { model: Article, type: object }
  
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
        
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

# generic rules
# please, remove them by adding more specific rules

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

default_api:
  url:   /:module/:action.:sf_format
