# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

cas:
  url: /cas
  param: { module: cas, action: login }

cas_logout:
  url: /cas/logout
  param: { module: cas, action: logout }
  
#Asso
assos_list:
  url:   /asso
  param: { module: asso, action: index }

assos_list_pole:
  url:   /asso/pole/:pole
  param: { module: asso, action: index }

assos_show:
  url:   /asso/:login
  class: sfDoctrineRoute
  param: { module: asso, action: show }
  options: { model: Asso, type: object, method_for_query: retrieveAsso }

asso_articles:
  url:   /asso/articles/:login
  class: sfDoctrineRoute
  param: { module: asso, action: articles }
  options: { model: Asso, type: object }

asso_events:
  url:   /asso/events/:login
  class: sfDoctrineRoute
  param: { module: asso, action: events }
  options: { model: Asso, type: object }

asso_bureau:
  url:   /asso/bureau/:login
  class: sfDoctrineRoute
  param: { module: asso, action: bureau }
  options: { model: Asso, type: object }

asso_trombi:
  url:   /asso/trombi/:login
  class: sfDoctrineRoute
  param: { module: asso, action: trombinoscope }
  options: { model: Asso, type: object }

asso_member:
  url:   /asso/membres/:login
  class: sfDoctrineRoute
  param: { module: asso, action: member }
  options: { model: Asso, type: object }

member_edit:
  url:   /asso/membres/:asso/edit/:id
  class: sfDoctrineRoute
  param: { module: member, action: edit }
  options: { model: AssoMember, type: object }
member_update:
  url:  /asso/membres/:asso/update/:id
  param: { module: member, action: update }
member_delete:
  url:  /asso/membres/:asso/delete/:id
  param: { module: member, action: delete }

asso_search:
  url:   /asso/search
  param: { module: asso, action: search }

asso_search_json:
  url:   /asso/search.json
  param: { module: asso, action: search, sf_format: json }

asso_edit:
  url: /asso/:login/edit
  class: sfDoctrineRoute
  param: { module: asso, action: edit }
  options: { model: Asso, type: object }
  
asso_join:
  url: /asso/:login/join
  class: sfDoctrineRoute
  param: { module: asso, action: join }
  options: { model: Asso, type: object }

asso_leave:
  url: /asso/:login/leave
  class: sfDoctrineRoute
  param: { module: asso, action: leave }
  options: { model: Asso, type: object }

asso_update:
  url: /asso/:id/update
  param: { module: asso, action: update }
    
#Articles
articles_list:
  url:   /article
  param: { module: article, action: index }
  
articles_list_asso:
  url:   /article/asso/:login
  class: sfDoctrineRoute
  param: { module: article, action: list }
  options: { model: Asso, type: object }
  
article_show:
  url:   /article/show/:id
  class: sfDoctrineRoute
  param: { module: article, action: show }
  options: { model: Article, type: object }

article_edit:
  url:  /article/edit/:id
  class: sfDoctrineRoute
  param: { module: article, action: edit }
  options: { model: Article, type: object }

article_update:
  url:  /article/update/:id
  param: { module: article, action: update }
  
article_delete:
  url:  /article/delete/:id
  param: { module: article, action: delete }   
article_create:
  url: /article/create
  param: { module: article, action: create } 
article_new:
  url: /article/:login/new
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: article, action: new }

#Events
events_list:
  url: /event.:sf_format
  param: { module: event, action: index }
  requirements:
    sf_format: (?:html|json)
  
events_list_asso:
  url:   /event/asso/:id
  class: sfDoctrineRoute
  param: { module: event, action: list }
  options: { model: Asso, type: object }
  
event_show:
  url: /event/show/:id
  class: sfDoctrineRoute
  param: { module: event, action: show }
  options: { model: Event, type: object }

event_edit:
  url: /event/edit/:id
  class: sfDoctrineRoute
  param: { module: event, action: edit }
  options: { model: Event, type: object }
  
event_update:
  url:  /event/update/:id
  param: { module: event, action: update }
  
event_delete:
  url:  /event/delete/:id
  param: { module: event, action: delete }   
event_create:
  url: /event/create
  param: { module: event, action: create } 
event_new:
  url: /event/:login/new
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: event, action: new }

agenda_detail:
  url:   /event/calendar
  param: { module: event, action: calendar }

#Materiel
materiel:
  url:   /materiel/asso/:login
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: materiel, action: index }

materiel_show:
  url:   /materiel/show/:id
  class: sfDoctrineRoute
  param: { module: materiel, action: show }
  options: { model: Materiel, type: object }

materiel_edit:
  url:  /materiel/edit/:id
  class: sfDoctrineRoute
  param: { module: materiel, action: edit }
  options: { model: Materiel, type: object }

materiel_update:
  url:  /materiel/update/:id
  param: { module: materiel, action: update }
  
materiel_delete:
  url:  /materiel/delete/:id
  class: sfDoctrineRoute
  param: { module: materiel, action: delete }
  options: { model: Materiel, type: object }

materiel_create:
  url: /materiel/create
  param: { module: materiel, action: create }

materiel_new:
  url: /materiel/:login/new
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: materiel, action: new }

materiel_ajout:
  url: /materiel/ajout/:id
  class: sfDoctrineRoute
  options: { model: Materiel, type: object }
  param: { module: materiel, action: ajout }

materiel_update_ajout:
  url:  /materiel/ajout/update/:id
  param: { module: materiel, action: updateAjout }

materiel_create_ajout:
  url: /materiel/ajout/create
  param: { module: materiel, action: createAjout }

#Emprunt
emprunt_delete:
  url:  /emprunt/delete/:id
  param: { module: emprunt, action: delete }

emprunt_create:
  url: /emprunt/create
  param: { module: emprunt, action: create }

emprunt_new:
  url: /emprunt/:id/new
  class: sfDoctrineRoute
  options: { model: Materiel, type: object }
  param: { module: emprunt, action: new }

emprunt_rendre:
  url: /emprunt/rendre/:id
  class: sfDoctrineRoute
  options: { model: Emprunt, type: object }
  param: { module: emprunt, action: rendre }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
        
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_register:
  url: /inscription
  param: { module: sfGuardRegister, action: index }

register_activation:
  url: /inscription/activation/:activation_key
  class: sfDoctrineRoute
  param: { module: sfGuardRegister, action: activation }
  options: { model: Activation, type: object }

register_resend:
  url: /inscription/activation
  param: { module: sfGuardRegister, action: resend }

gesmail:
  url: /asso/:login/gesmail
  class: sfDoctrineRoute
  param: { module: gesmail, action: index }
  options: { model: Asso, type: object }

gesmail_box:
  url: /asso/:login/gesmail/:box
  class: sfDoctrineRoute
  param: { module: gesmail, action: index }
  options: { model: Asso, type: object }
  
gesmail_box_delete:
  url: /asso/:login/gesmail/delete/:box
  param: { module: gesmail, action: delete }

# generic rules
# please, remove them by adding more specific rules

#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*