# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        BDE-UTC : Portail des associations
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       noindex, nofollow

  stylesheets:    [jquery-ui-1.8.12.custom.css, bootstrap.min.css, main.css, carousel.css]

  javascripts:    [jquery-1.7.2.min.js, jquery-ui-1.8.12.custom.min.js, bootstrap.min.js, search.js, jquery.contentcarousel.js, main.js]

  has_layout:     true
  layout:         layout
