generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Role
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          role
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        droits: { help: "* 0x01 - modification de l'asso * 0x02 - gestion des membres * 0x04 - gestion des articles *  0x08 - gestion des events *  0x10 - gestion des roles *  0x20 - changement de pres" }
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
