generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CharteLocaux
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          charte_locaux
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        title: "Chartes d'accès étendu aux locaux"
        display: [id, date, Responsable, asso, semestre, CharteLocauxType, statut_string, motif]
        actions: {}
        batch_actions: {}
        object_actions: {valider: ~, refuser:~, _delete:~}
        sort: [date, desc]
      filter:
        display: [login, user_id, asso_id, semestre_id, type_id, statut]
      form:    ~
      edit:    ~
      new:     ~
