# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: asso, action: index }

cas:
  url: /cas
  param: { module: cas, action: login }

cas_logout:
  url: /cas/logout
  param: { module: cas, action: logout }

# Budget

budget_list:
  url: /budget/asso/:login
  class: sfDoctrineRoute
  param: { module: budget, action: index }
  options: { model: Asso, type: object }

budget_new:
  url: /budget/new/:login
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: budget, action: new }

budget_show:
  url: /budget/show/:id
  class: sfDoctrineRoute
  param: { module: budget, action: show }
  options: { model: Budget, type: object }

budget_update:
  url:  /budget/update/:id
  param: { module: budget, action: update }

budget_edit:
  url:  /budget/edit/:id
  class: sfDoctrineRoute
  param: { module: budget, action: edit }
  options: { model: Budget, type: object }

budget_delete:
  url:  /budget/delete/:id
  class: sfDoctrineRoute
  param: { module: budget, action: delete }
  options: { model: Budget, type: object }

budget_create:
  url: /budget/create
  param: { module: budget, action: create }

# Comptes

compte:
  url:   /compte/asso/:login
  class: sfDoctrineRoute
  param: { module: compte, action: index }
  options: { model: Asso, type: object }

compte_edit:
  url:  /compte/edit/:id
  class: sfDoctrineRoute
  param: { module: compte, action: edit }
  options: { model: Article, type: object }

compte_update:
  url:  /compte/update/:id
  param: { module: compte, action: update }

compte_delete:
  url:  /compte/delete/:id
  param: { module: compte, action: delete }

compte_new:
  url: /compte/new/:login
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: compte, action: new }

compte_create:
  url: /compte/create
  param: { module: compte, action: create }

# BudgetPoste

budget_poste_new:
  url: /budget/poste/new/:budget/:categorie
  param: { module: budgetPoste, action: new }

budget_poste_update:
  url:  /budget/poste/update/:id
  param: { module: budgetPoste, action: update }

budget_poste_edit:
  url:  /budget/poste/edit/:id
  class: sfDoctrineRoute
  param: { module: budgetPoste, action: edit }
  options: { model: BudgetPoste, type: object }

budget_poste_delete:
  url:  /budget/poste/delete/:id
  class: sfDoctrineRoute
  param: { module: budgetPoste, action: delete }
  options: { model: BudgetPoste, type: object }

budget_poste_create:
  url: /budget/poste/create
  param: { module: budgetPoste, action: create }
