# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: asso, action: index }

cas:
  url: /cas
  param: { module: cas, action: login }

cas_logout:
  url: /cas/logout
  param: { module: cas, action: logout }

# Budget

budget_list:
  url: /budget/asso/:login
  class: sfDoctrineRoute
  param: { module: budget, action: index }
  options: { model: Asso, type: object }

budget_new:
  url: /budget/new/:login
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: budget, action: new }

budget_show:
  url: /budget/show/:id
  class: sfDoctrineRoute
  param: { module: budget, action: show }
  options: { model: Budget, type: object }

budget_update:
  url:  /budget/update/:id
  param: { module: budget, action: update }

budget_edit:
  url:  /budget/edit/:id
  class: sfDoctrineRoute
  param: { module: budget, action: edit }
  options: { model: Budget, type: object }

budget_delete:
  url:  /budget/delete/:id
  class: sfDoctrineRoute
  param: { module: budget, action: delete }
  options: { model: Budget, type: object }

budget_create:
  url: /budget/create
  param: { module: budget, action: create }
