# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: budgetPrevisionnel, action: index }

cas:
  url: /cas
  param: { module: cas, action: login }

cas_logout:
  url: /cas/logout
  param: { module: cas, action: logout }

budget_previsionnel:
  class: sfDoctrineRouteCollection
  options:
    model:                Budget
    module:               budgetPrevisionnel
    prefix_path:          /budget_previsionnel
    column:               id
    with_wildcard_routes: true

compte:
  url:   /compte/asso/:login
  class: sfDoctrineRoute
  param: { module: compte, action: index }
  options: { model: Asso, type: object }

compte_edit:
  url:  /compte/edit/:id
  class: sfDoctrineRoute
  param: { module: compte, action: edit }
  options: { model: Article, type: object }

compte_update:
  url:  /compte/update/:id
  param: { module: compte, action: update }

compte_delete:
  url:  /compte/delete/:id
  param: { module: compte, action: delete }

compte_new:
  url: /compte/new/:login
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: compte, action: new }

compte_create:
  url: /compte/create
  param: { module: compte, action: create }
