# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: asso, action: index }

cas:
  url: /cas
  param: { module: cas, action: login }

cas_logout:
  url: /cas/logout
  param: { module: cas, action: logout }
    
transaction:
  url:   /transaction/asso/:login
  class: sfDoctrineRoute
  param: { module: transaction, action: index }
  options: { model: Asso, type: object }

transaction_edit:
  url:  /transaction/edit/:id
  class: sfDoctrineRoute
  param: { module: transaction, action: edit }
  options: { model: Transaction, type: object }

transaction_update:
  url:  /transaction/update/:id
  param: { module: transaction, action: update }

transaction_delete:
  url:  /transaction/delete/:id
  param: { module: transaction, action: delete }
  
transaction_create:
  url: /transaction/create
  param: { module: transaction, action: create }
  
transaction_new:
  url: /transaction/:login/new
  class: sfDoctrineRoute
  options: { model: Asso, type: object }
  param: { module: transaction, action: new }