# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  cas:
    # Exemple for https://cas-server-name:8443/cas-path
    server_name: 'cas.utc.fr'
    server_port: 443
    server_path: 'cas'
    # SSL certificat location, can be:
    #  relative to sf_root_dir, ex:    "data/cas/cert/mycert.pem"
    #  absolute ex:                    "/usr/var/certif/xxx.pem"
    #  disabled for dev context ex:    false
    server_cert: "../data/cas.pem"
  sfImageTransformPlugin:
    default_adapter: GD
    default_image: default.jpg
    mime_type:
      auto_detect: true
      library: gd_mime_type
  portail:
    current_semestre: 2
    default_join_role: 3
    ginger_key: abc