generator:
  class: sfDoctrineGenerator
  param:
    model_class:           CharteInfo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          charte_info
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        title: "Chartes"
        display: [id, date, Semestre, Asso, Responsable, confirmation]
        actions: {}
        batch_actions: {}
        object_actions: {}
      filter:
        display: [semestre_id, asso_id, responsable_id, confirmation]
      form:    ~
      edit:    ~
      new:     ~
