Asso:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(50) }
    login: { type: string(32) }
    pole_id: { type: integer }
    type_id: { type: integer }
    url_site: { type: string(100) }
    description: { type: string }
    logo: { type: string(100) }
    active: { type: boolean }
    passation: { type: boolean }
    salle: { type: string(6) }
    phone: { type: string(15) }
    facebook: { type: string }
  relations:
    Pole: { local: pole_id, foreign: id }
    Type: { local: type_id, foreign: id, class: TypeAsso }
 
Pole:
  connection: doctrine
  columns:
    asso_id: { type: integer }
    couleur: { type: string(7) }
  relations:
    Infos: { local: asso_id, foreign: id, class: Asso, foreignAlias: PoleInfos }
    
TypeAsso:
  connection: doctrine
  columns:
    name: { type: string(50) }
    
AssoMember:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    user_id: { type: integer }
    asso_id: { type: integer }
    role_id: { type: integer }
    semestre_id: { type: integer }
  relations:
    Asso: { local: asso_id, foreign: id }
    Role: { local: role_id, foreign: id }
    User: { local: user_id, foreign: id, class: sfGuardUser }
    Semestre: { local: semestre_id, foreign: id }
    
Role:
  connection: doctrine
  columns:
    name: { type: string(50) }
    sort: { type: integer(4) }
      
Profile:
   connection: doctrine
   actAs: { Timestampable: ~ }
   columns:
     user_id: { type: integer }
     domain: { type: string(15) }
     nickname: { type: string(50) }
     birthday: { type: date }
     sexe: { type: char(1) }
     mobile: { type: string(15) }
     home_place: { type: integer }
     family_place: { type: integer }
     branche_id: { type: integer }
     filiere_id: { type: integer }
     semestre: { type: integer }
     other_email: { type: string }
     photo: { type: string }
     weekmail: { type: boolean }
     autorisation_photo: { type: boolean }
     cotisant: { type: boolean }
   relations:
     User: { local: user_id, foreign: id, class: sfGuardUser, foreignType: one }
     HomePlace: { local: home_place, foreign: id, class: Place }
     FamilyPlace: { local: family_place, foreign: id, class: Place }
     Branche: { local: branche_id, foreign: id }

Place:
   connection: doctrine
   actAs: { Timestampable: ~ }
   columns:
     street: { type: string }
     zipcode: { type: string(10) }
     city: { type: string(100) }
     country: { type: string(100) }
     phone: { type: string(15) }

Event:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    asso_id : { type: integer }
    type_id: { type: integer }
    name: { type: string(50) }
    description: { type: string }
    start_date: { type: timestamp }
    end_date: { type: timestamp }
    is_public: { type: boolean }
    is_weekmail: { type: boolean }
    place: { type: string }
    affiche: { type: string }
  relations:
    Asso: { local: asso_id, foreign: id }
    Type: { local: type_id, foreign: id, class: EventType }
    
EventType:
  connection: doctrine
  columns:
    name: { type: string(50) }
    color: { type: string(7) }
    
Article:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    asso_id: { type: integer }
    name : { type: string(200) }
    text : { type: string }
    is_weekmail: { type: boolean }
    image: { type: string }
  relations:
    Asso: { local: asso_id, foreign: id }

Semestre:
  connection: doctrine
  columns:
    name: { type: string(3) }
    
Branche:
  connection: doctrine
  columns:
    name: { type: string(3) }

Activation:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    user_id: { type: integer }
    activation_key: { type: string }
  relations:
    sfGuardUser: { onUpdate: CASCADE, local: user_id, foreign: id, foreignAlias: Activations}