Asso:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(50) }
    login: { type: string(32) }
    pole_id: { type: integer }
    type_id: { type: integer }
    url_site: { type: string(100) }
    description: { type: string }
    logo: { type: string(100) }
    active: { type: boolean }
  relations:
    Pole: { local: pole_id, foreign: id }
    Type: { local: type_id, foreign: id, class: TypeAsso }
 
Pole:
  connection: doctrine
  columns:
    asso_id: { type: integer }
  relations:
    Infos: { local: asso_id, foreign: id, class: Asso }
    
    
TypeAsso:
  connection: doctrine
  columns:
    name: { type: string(50) }
    
AssoMember:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    user_id: { type: integer }
    asso_id: { type: integer }
    role_id: { type: integer }
  relations:
    Asso: { local: asso_id, foreign: id }
    Role: { local: role_id, foreign: id }
    User: { local: user_id, foreign: id, class: sfGuardUser }
    
Role:
  connection: doctrine
  columns:
    name: { type: string(50) }
    sort: { type: integer(4) }
      
Profile:
   connection: doctrine
   actAs: { Timestampable: ~ }
   columns:
     user_id: { type: integer }
     domain: { type: string(15) }
     nickname: { type: string(50) }
     birthday: { type: date }
     sexe: { type: char(1) }
     mobile: { type: string(15) }
     home_place: { type: integer }
     family_place: { type: integer }
   relations:
     User: { local: user_id, foreign: id, class: sfGuardUser, foreignType: one }
     HomePlace: { local: home_place, foreign: id, class: Place }
     FamilyPlace: { local: family_place, foreign: id, class: Place }

Place:
   connection: doctrine
   actAs: { Timestampable: ~ }
   columns:
     street: { type: string }
     zipcode: { type: string(10) }
     city: { type: string(100) }
     country: { type: string(100) }
     phone: { type: string(15) }

Event:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    asso_id : { type: integer }
    type_id: { type: integer }
    name: { type: string(50) }
    description: { type: string }
    start_date: { type: date }
    end_date: { type: date }
    is_public: { type: boolean }
    is_weekmail: { type: boolean }
    place: { type: string }
  relations:
    Asso: { local: asso_id, foreign: id }
    Type: { local: type_id, foreign: id, class: EventType }
    
EventType:
  connection: doctrine
  columns:
    name: { type: string(50) }
    color: { type: string(7) }
    
Article:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    asso_id: { type: integer }
    name : { type: string(200) }
    text : { type: string }
    is_weekmail: { type: boolean }
  relations:
    Asso: { local: asso_id, foreign: id }
