options:
  collate: utf8_unicode_ci
  charset: utf8
  
Asso:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(50) }
    login: { type: string(32) }
    pole_id: { type: integer }
    type_id: { type: integer }
    url_site: { type: string(100) }
    description: { type: string }
    logo: { type: string(100) }
    active: { type: boolean }
    passation: { type: boolean }
    salle: { type: string(6) }
    phone: { type: string(15) }
    facebook: { type: string(100) }
    summary: { type: string(150) }
  relations:
    Pole: { local: pole_id, foreign: id }
    Type: { local: type_id, foreign: id, class: TypeAsso }

Album:
  connection: doctrine
  actAs: { Timestampable: ~}
  columns:
    name: { type: string(50) }
    location: { type: string(100) }
    visibility: { type: integer }
    asso_id: { type: integer }
  relations:
    Asso: { local: asso_id, foreign: id }
    Images:
      type: many
      class: Image
      local: id
      foreign: album_id
      onDelete: CASCADE
Image:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(50) }
    legend: { type: string(255) }
    album_id: { type: integer }
  relations:
    Album: { local: album_id, foreign: id, type : one }

Pole:
  connection: doctrine
  columns:
    asso_id: { type: integer }
    couleur: { type: string(7) }
  relations:
    Infos: { local: asso_id, foreign: id, class: Asso, foreignAlias: PoleInfos, foreignType: one }
    
TypeAsso:
  connection: doctrine
  columns:
    name: { type: string(50) }
    
AssoMember:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    user_id: { type: integer }
    asso_id: { type: integer }
    role_id: { type: integer }
    semestre_id: { type: integer }
  relations:
    Asso: { local: asso_id, foreign: id }
    Role: { local: role_id, foreign: id }
    User: { local: user_id, foreign: id, class: sfGuardUser }
    Semestre: { local: semestre_id, foreign: id }
    
Role:
  connection: doctrine
  columns:
    name: { type: string(50) }
    sort: { type: integer(4) }
    bureau: { type: boolean, default: false, notnull: true }
    droits: { type: integer, default: 0, notnull: true }
 
Profile:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    user_id: { type: integer }
    domain: { type: string(15) }
    nickname: { type: string(50) }
    birthday: { type: date }
    sexe: { type: char(1) }
    mobile: { type: string(15) }
    home_place: { type: integer }
    family_place: { type: integer }
    branche_id: { type: integer }
    filiere_id: { type: integer }
    semestre: { type: integer }
    other_email: { type: string }
    photo: { type: string }
    weekmail: { type: boolean }
    autorisation_photo: { type: boolean }
    devise: { type: string(300) }

  relations:
    User: { local: user_id, foreign: id, class: sfGuardUser, foreignType: one }
    HomePlace: { local: home_place, foreign: id, class: Place }
    FamilyPlace: { local: family_place, foreign: id, class: Place }
    Branche: { local: branche_id, foreign: id }
    Filiere: { local: filiere_id, foreign: id }

UserSemestre:
  connection: doctrine
  columns:
    user_id: { type: integer }
    branche_id: { type: integer }
    num: { type: string(4) }
    abroad: { type: string(30) }
    semestre_id: {type: integer }

  relations:
    Profile: { local: user_id, foreign: id }
    Branche: { local: branche_id, foreign: id }
    Semestre: { local: semestre_id, foreign: id }

UserUv:
  connection: doctrine
  columns:
    uv_id: { type: integer }
    user_semestre_id: { type: integer }
    note: { type: string(2) }
 
  relations:
    Uv: { local: uv_id, foreign: id }
    UserSemestre: { local: user_semestre_id, foreign: id }

UserSport:
  connection: doctrine
  columns:
    user_id: { type: integer }
    sport_id: { type: integer }
 
  relations:
    Profile: { local: user_id, foreign: id }
    Sport: { local: sport_id, foreign: id }

Sport:
  connection: doctrine
  columns:
    name: { type: string(30), notnull: true }
 
Uv:
  connection: doctrine
  columns:
    code: { type: string(4), unique:true}
    name: { type: string(100) }

Place:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    street: { type: string }
    zipcode: { type: string(10) }
    city: { type: string(100) }
    country: { type: string(100) }
    phone: { type: string(15) }

Event:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    asso_id : { type: integer, notnull: true }
    type_id: { type: integer, notnull: true }
    name: { type: string(50), notnull: true }
    description: { type: string, notnull: true }
    start_date: { type: timestamp, notnull: true }
    end_date: { type: timestamp, notnull: true }
    is_public: { type: boolean, default: true }
    is_weekmail: { type: boolean, default: false }
    place: { type: string }
    affiche: { type: string }
    summary: { type: string(150) }
  relations:
    Asso: { local: asso_id, foreign: id }
    Type: { local: type_id, foreign: id, class: EventType }
    
EventType:
  connection: doctrine
  columns:
    name: { type: string(50) }
    color: { type: string(7) }
    
Article:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    asso_id: { type: integer, notnull: true }
    name : { type: string(200), notnull: true }
    text : { type: string, notnull: true }
    is_weekmail: { type: boolean, default: false }
    image: { type: string }
    summary: { type: string(150) }
  relations:
    Asso: { local: asso_id, foreign: id }

Semestre:
  connection: doctrine
  columns:
    name: { type: string(3) }
    
Branche:
  connection: doctrine
  columns:
    name: { type: string(3) }
    
Filiere:
  connection: doctrine
  columns:
    name: { type: string(10) }

Activation:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    user_id: { type: integer }
    activation_key: { type: string }
  relations:
    sfGuardUser: { onUpdate: CASCADE, local: user_id, foreign: id, foreignAlias: Activations}
   
Abonnement:
  connection: doctrine
  actAs: { Timestampable: ~ }
  columns:
    user_id: { type: integer, notnull: true }
    asso_id: { type: integer } 
    type_publication: { type: integer, notnull: true }
  relations:
    Asso: { local: asso_id, foreign: id }
    User: { local: user_id, foreign: id, class: sfGuardUser }  
    
